/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;   // ✅ 正确的 Statement

    import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class CustomerList extends javax.swing.JFrame {   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerList.class.getName());

    /**
     * Creates new form CustomerList
     */
    public CustomerList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ListOfCustomer = new javax.swing.JLabel();
        NewCustomer = new javax.swing.JPanel();
        CustomerN = new javax.swing.JLabel();
        CustomerName = new javax.swing.JTextField();
        LabelContactNumber = new javax.swing.JLabel();
        ContactNumber = new javax.swing.JTextField();
        LabelCustomerID = new javax.swing.JLabel();
        CusID = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        AddFunction = new javax.swing.JButton();
        ClearFunction = new javax.swing.JButton();
        cupdate = new javax.swing.JButton();
        cDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        cview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        ListOfCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListOfCustomer.setText("Lisf of Customer");

        NewCustomer.setBackground(new java.awt.Color(255, 255, 255));
        NewCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("NewCustomer"));

        CustomerN.setText("Customer Name");

        LabelContactNumber.setText("Contact Number");

        ContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberActionPerformed(evt);
            }
        });

        LabelCustomerID.setText("Customer ID");

        LabelEmail.setText("Email");

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        AddFunction.setText("Add");
        AddFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFunctionActionPerformed(evt);
            }
        });

        ClearFunction.setText("Clear");
        ClearFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFunctionActionPerformed(evt);
            }
        });

        cupdate.setText("Update");
        cupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewCustomerLayout = new javax.swing.GroupLayout(NewCustomer);
        NewCustomer.setLayout(NewCustomerLayout);
        NewCustomerLayout.setHorizontalGroup(
            NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewCustomerLayout.createSequentialGroup()
                        .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerN, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCustomerID)
                            .addComponent(CusID, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(NewCustomerLayout.createSequentialGroup()
                        .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewCustomerLayout.createSequentialGroup()
                                .addComponent(AddFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ClearFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CustomerName)
                                .addComponent(LabelContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ContactNumber)
                                .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        NewCustomerLayout.setVerticalGroup(
            NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCustomerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LabelCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(CusID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomerN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewCustomerLayout.createSequentialGroup()
                        .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddFunction)
                            .addComponent(ClearFunction))
                        .addGap(34, 34, 34))
                    .addGroup(NewCustomerLayout.createSequentialGroup()
                        .addComponent(cupdate)
                        .addContainerGap())))
        );

        cDelete.setText("Delete");

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CusID", "CustomerName", "ContactNumber", "Email"
            }
        ));
        CustomerTable.setGridColor(new java.awt.Color(255, 255, 255));
        CustomerTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        CustomerTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        cview.setText("View");
        cview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ListOfCustomer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cview))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListOfCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cDelete)
                            .addComponent(cview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void AddFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFunctionActionPerformed
        // TODO add your handling code here:
        
        String CuID =CusID.getText();
        String CusN = CustomerName.getText();
        String ContactN=ContactNumber.getText();
        String El=Email.getText();
        
        int CNO = Integer.parseInt(CuID);
        //connection
        
        try{
            //open connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CarRentalSystem?useSSL=false&serverTimezone=UTC", "root", "Mandatary#123");
           
            //Insert customer data in database
             String sql = "INSERT INTO customerlist (CusID, CustomerName, ContactNumber, Email) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(CuID));
        pst.setString(2, CusN);
        pst.setString(3, ContactN);
        pst.setString(4, El);
        
        //proceed
        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Customer added successfully!");
        }
        
        //clear word
            CusID.setText("");
            CustomerName.setText("");
            ContactNumber.setText("");
            Email.setText("");
            
            CustomerTable();
  
        // close connection
        pst.close();
        con.close();
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_AddFunctionActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
   int selectedRow = CustomerTable.getSelectedRow();
        if (selectedRow != -1) {
            // 把表格里的值填到输入框
            CusID.setText(CustomerTable.getValueAt(selectedRow, 0).toString());
            CustomerName.setText(CustomerTable.getValueAt(selectedRow, 1).toString());
            ContactNumber.setText(CustomerTable.getValueAt(selectedRow, 2).toString());
            Email.setText(CustomerTable.getValueAt(selectedRow, 3).toString());
    // Get values from the selected row
        }
        
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void cviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cviewActionPerformed
        // TODO add your handling code here:
        
        //open connection
       try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/CarRentalSystem?useSSL=false&serverTimezone=UTC",
            "root", 
            "Mandatary#123"
        );

        Statement st = con.createStatement();
        String sql = "SELECT * FROM customerlist";
        ResultSet rs = st.executeQuery(sql);

        javax.swing.table.DefaultTableModel tb1Model = 
            (javax.swing.table.DefaultTableModel) CustomerTable.getModel();
        tb1Model.setRowCount(0); // 清空旧数据

        while (rs.next()) {
            String CusID = String.valueOf(rs.getInt("CusID"));
            String CustomerName = rs.getString("CustomerName");
            String ContactNumber = rs.getString("ContactNumber");
            String Email = rs.getString("Email");

            String tbdata[] = {CusID, CustomerName, ContactNumber, Email};
            tb1Model.addRow(tbdata);
        }

        rs.close();
        st.close();
        con.close();

    } catch (Exception g) {
        System.out.println(g.getMessage());
        JOptionPane.showMessageDialog(this, "加载数据失败: " + g.getMessage());
    }
    }//GEN-LAST:event_cviewActionPerformed

    private void ClearFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFunctionActionPerformed
        // TODO add your handling code here:
         CusID.setText("");
        CustomerName.setText("");
        ContactNumber.setText("");
        Email.setText("");
    }//GEN-LAST:event_ClearFunctionActionPerformed

    private void cupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupdateActionPerformed
        // TODO add your handling code here:
         if (CusID.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Please select a row to update.");
        return;
    }
    }//GEN-LAST:event_cupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerList().setVisible(true));
    }

    
   public void CustomerTable() {
    try {
        // 1. 连接数据库
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/CarRentalSystem?useSSL=false&serverTimezone=UTC",
            "root",
            "Mandatary#123"
        );

        // 2. 查询所有数据
        String sql = "SELECT * FROM customerlist";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        // 3. 获取 JTable 的 model
        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) CustomerTable.getModel();
        model.setRowCount(0); // 清空旧数据

        // 4. 把结果集逐行加入 JTable
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("CusID"),
                rs.getString("CustomerName"),
                rs.getString("ContactNumber"),
                rs.getString("Email")
            });
        }

        // 5. 关闭连接
        rs.close();
        pst.close();
        con.close();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "加载数据出错: " + ex.getMessage());
        ex.printStackTrace();
    }           
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFunction;
    private javax.swing.JButton ClearFunction;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JTextField CusID;
    private javax.swing.JLabel CustomerN;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel LabelContactNumber;
    private javax.swing.JLabel LabelCustomerID;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel ListOfCustomer;
    private javax.swing.JPanel NewCustomer;
    private javax.swing.JButton cDelete;
    private javax.swing.JButton cupdate;
    private javax.swing.JButton cview;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
