
package carrental;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Message1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        AdminLogin = new javax.swing.JButton();
        UserLogin = new javax.swing.JButton();
        LoginPage = new javax.swing.JLabel();
        Message2 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Message1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Message1.setForeground(new java.awt.Color(0, 0, 0));
        Message1.setText("Username");
        Message1.setPreferredSize(new java.awt.Dimension(65, 32));
        jPanel1.add(Message1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, 30));

        Username.setBackground(new java.awt.Color(255, 255, 255));
        Username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setPreferredSize(new java.awt.Dimension(65, 32));
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 300, 30));

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setPreferredSize(new java.awt.Dimension(65, 32));
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 300, 30));

        AdminLogin.setBackground(new java.awt.Color(255, 255, 255));
        AdminLogin.setForeground(new java.awt.Color(0, 0, 0));
        AdminLogin.setText("Login as Admin");
        AdminLogin.setPreferredSize(new java.awt.Dimension(132, 23));
        AdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginActionPerformed(evt);
            }
        });
        jPanel1.add(AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        UserLogin.setBackground(new java.awt.Color(255, 255, 255));
        UserLogin.setForeground(new java.awt.Color(0, 0, 0));
        UserLogin.setText("Login as User");
        UserLogin.setPreferredSize(new java.awt.Dimension(132, 23));
        jPanel1.add(UserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        LoginPage.setBackground(new java.awt.Color(0, 0, 0));
        LoginPage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LoginPage.setForeground(new java.awt.Color(0, 0, 0));
        LoginPage.setText("Login Page");
        jPanel1.add(LoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 130, -1));

        Message2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Message2.setForeground(new java.awt.Color(0, 0, 0));
        Message2.setText("Password");
        Message2.setPreferredSize(new java.awt.Dimension(65, 32));
        jPanel1.add(Message2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 120, 30));

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setForeground(new java.awt.Color(0, 0, 0));
        Exit.setText("Exit");
        Exit.setPreferredSize(new java.awt.Dimension(132, 23));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLoginActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLogin;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel LoginPage;
    private javax.swing.JLabel Message1;
    private javax.swing.JLabel Message2;
    private javax.swing.JTextField Password;
    private javax.swing.JButton UserLogin;
    private javax.swing.JTextField Username;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
