
package carrental.ui;

import carrental.util.DatabaseConnection;
import carrental.model.*;
import carrental.dao.*;
import carrental.ui.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Message1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        UserLogin = new javax.swing.JButton();
        LoginPage = new javax.swing.JLabel();
        Message2 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Message1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Message1.setText("Username");
        Message1.setPreferredSize(new java.awt.Dimension(65, 32));
        getContentPane().add(Message1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 30));

        Username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Username.setPreferredSize(new java.awt.Dimension(65, 40));
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 290, 40));

        UserLogin.setText("Login");
        UserLogin.setPreferredSize(new java.awt.Dimension(132, 23));
        UserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLoginActionPerformed(evt);
            }
        });
        getContentPane().add(UserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 160, 30));

        LoginPage.setBackground(new java.awt.Color(0, 204, 204));
        LoginPage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LoginPage.setText("Login Page");
        getContentPane().add(LoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        Message2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Message2.setText("Password");
        Message2.setPreferredSize(new java.awt.Dimension(65, 32));
        getContentPane().add(Message2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, 30));

        Exit.setText("Cancel");
        Exit.setPreferredSize(new java.awt.Dimension(132, 23));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        Password.setPreferredSize(new java.awt.Dimension(65, 40));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 290, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CarBackground.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        //Cancel Buttton
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed

    }//GEN-LAST:event_UsernameActionPerformed
  
    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void UserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLoginActionPerformed
        // TODO add your handling code here:
        if(Username.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill out the Username");
        }
        else if (Password.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill out the Password");
        }
        else{
            String username = Username.getText();
            String password = new String(Password.getPassword());
            
            UserDAO dao = new UserDAO();
            User user = dao.getUserByUsernameAndPassword(username, password);

            if (user != null) {
                 JOptionPane.showMessageDialog(null, "Login success: " + user.getUsername());
                 
                 if(user.getRole().toLowerCase().equals("staff")){
                     StaffDashboard staffDashboard = new StaffDashboard(user);
                     staffDashboard.setVisible(true);
                 }else if(user.getRole().toLowerCase().equals("admin")){
                     AdminPage adminPage =  new AdminPage();
                     adminPage.setVisible(true);
                 }else{
                      JOptionPane.showMessageDialog(null, "Role not found");
                 }
            } else {
                JOptionPane.showMessageDialog(null, "Login Failed");
            }
        }
    }//GEN-LAST:event_UserLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel LoginPage;
    private javax.swing.JLabel Message1;
    private javax.swing.JLabel Message2;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton UserLogin;
    private javax.swing.JTextField Username;
    // End of variables declaration//GEN-END:variables
}
